name: jangnkangho
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  # Flutter SDK 버전을 3.0.0 이상으로 설정합니다.
  sdk: '>=3.0.0 <4.0.0' 

# 'dependencies:' 키워드부터 시작합니다.
dependencies:
  # 'flutter:'는 dependencies보다 2칸 더 들여씁니다.
  flutter:
    # 'sdk:'는 flutter:보다 2칸 더 들여씁니다.
    sdk: flutter

  # --- UI & Utilities ---
  # 아래 모든 패키지는 'flutter:'와 같은 레벨(2칸)로 들여씁니다.
  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0

  # --- State Management ---
  provider: ^6.1.5+1
  
  # --- Firebase Services ---
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2       
  #google_sign_in: ^7.2.0     
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4


# 'dev_dependencies:' 키워드는 'dependencies:'와 같은 레벨(0칸)입니다.
dev_dependencies:
  # 'flutter_test:'는 dev_dependencies:보다 2칸 들여씁니다.
  flutter_test:
    # 'sdk:'는 flutter_test:보다 2칸 들여씁니다.
    sdk: flutter

  # 아래 패키지는 flutter_test:와 같은 레벨(2칸)입니다.
  flutter_lints: ^6.0.0

# 'flutter:' 키워드는 'dependencies:'와 같은 레벨(0칸)입니다.
flutter:

  # 'uses-material-design:'은 flutter:보다 2칸 들여씁니다.
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf