// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_wYPgjHUqzT6OYX8bO86zBmIroJOCqc',
    appId: '1:479534436388:web:6f33eb299920e73b4ec8b1',
    messagingSenderId: '479534436388',
    projectId: 'jangnkangho',
    authDomain: 'jangnkangho.firebaseapp.com',
    storageBucket: 'jangnkangho.firebasestorage.app',
    measurementId: 'G-65D0W63K2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDqYG6Ln-cHzC8u5LSuNx9dAvs9_brGKc',
    appId: '1:479534436388:android:e5e26fb6b8be27994ec8b1',
    messagingSenderId: '479534436388',
    projectId: 'jangnkangho',
    storageBucket: 'jangnkangho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwkWjYVwiWbcCazd97jZO5pRBxcOyZOno',
    appId: '1:479534436388:ios:c98df4e68b8e0ab84ec8b1',
    messagingSenderId: '479534436388',
    projectId: 'jangnkangho',
    storageBucket: 'jangnkangho.firebasestorage.app',
    androidClientId: '479534436388-t1cjl3gt5qd5h3eolo9lksjs2c5ucnv9.apps.googleusercontent.com',
    iosClientId: '479534436388-5vkj21dr7atf44bp0oqupi29ifos6gjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jangnkangho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwkWjYVwiWbcCazd97jZO5pRBxcOyZOno',
    appId: '1:479534436388:ios:c98df4e68b8e0ab84ec8b1',
    messagingSenderId: '479534436388',
    projectId: 'jangnkangho',
    storageBucket: 'jangnkangho.firebasestorage.app',
    androidClientId: '479534436388-t1cjl3gt5qd5h3eolo9lksjs2c5ucnv9.apps.googleusercontent.com',
    iosClientId: '479534436388-5vkj21dr7atf44bp0oqupi29ifos6gjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jangnkangho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7_wYPgjHUqzT6OYX8bO86zBmIroJOCqc',
    appId: '1:479534436388:web:5e35940d62497c974ec8b1',
    messagingSenderId: '479534436388',
    projectId: 'jangnkangho',
    authDomain: 'jangnkangho.firebaseapp.com',
    storageBucket: 'jangnkangho.firebasestorage.app',
    measurementId: 'G-4HMFC3YM0G',
  );
}
